### ISSUE TITLE
如何载入poco-SDK到项目目录里，照着文档做poco辅助窗没有出现渲染树啊

### ISSUE THREAD

**Issue by 15957179764** [AirtestProject/Poco-SDK#19]
![image](https://user-images.githubusercontent.com/40204090/41290339-2b97bba4-6e7f-11e8-87f1-b244a57d1653.png)
也试过把里面每个文件都单独放在安装目录里，也没用
![image](https://user-images.githubusercontent.com/40204090/41290388-54764f7c-6e7f-11e8-819f-1fe2dd8010e0.png)
进入airtest中，log查看窗只有这一个提示，连接的是mumu模拟器，运行的是一款cocos2d lua游戏
![image](https://user-images.githubusercontent.com/40204090/41290510-ac7a1d52-6e7f-11e8-95c0-c696917c3048.png)
中间代码复制到airtest后，运行报错的，应该怎么操作啊，新人求指点~~~~

**Comment by adolli** [comment]
请问你将poco-sdk放到游戏代码里了吗？
