### ISSUE TITLE
The file of cocos2d-x lua is empty

### ISSUE THREAD

**Issue by QSJZKADMaomaotu** [AirtestProject/Poco-SDK#2]
download the  cocos2d-x,the file is empty

**Comment by geonsme** [comment]
me too

**Comment by Meteorix** [comment]
We are working on it. A complete tutorial is coming soon.

**Comment by adolli** [comment]
SDK for cocos2dx-lua is comming! see [docs](http://poco.readthedocs.io/en/latest/source/doc/integration.html#cocos2dx-lua). Any issues please let us know.
