### ISSUE TITLE
quick lua cocos2.26 版，已经提示连接成功，针对3.0的文档也改了所有接口，但是获取不到UI信息

### ISSUE THREAD

**Issue by jinyindao** [AirtestProject/Poco-SDK#25]
![6s 7w bpn28edjldc6p ri](https://user-images.githubusercontent.com/19818468/45085595-a08f6280-b133-11e8-8a0b-0aae8af325cd.jpg)

**Comment by jinyindao** [comment]
这有办法接入这个版本吗？

**Comment by adolli** [comment]
可以提供更详细的信息吗？你可以先在game里面调试每个接口的返回值是否正确，然后再通过poco执行远程调用。

**Comment by zhaoxianning** [comment]
你可以用了吗？我们也是2.26的版本，现在正在搞，我也是一头雾水

**Comment by zhaoxianning** [comment]
549445794  可以加我下QQ吗？谢谢了~~~~
