### ISSUE TITLE
[<Unity>-Poco-SDK] The namespace `Poco' already contains a definition for `UnityNode'

### ISSUE THREAD

**Issue by sanjusangal** [AirtestProject/Poco-SDK#33]
I am trying to intergrate poco sdk into my project.
I copied the Unity3D folder into my scripts folder of unity project and deleted the ngui folder. 
My console shows error:
Assets/Unity3D/ugui/UnityNode.cs(9,15): error CS0101: The namespace `Poco' already contains a definition for `UnityNode'

**Comment by elizabethqny** [comment]
I'm not sure you used same Poco-SDK as I did, but if you did, deleting "fairygui" solves the problem.

**Comment by adolli** [comment]
I'm sorry for forgetting to update the documents. As we provided 3 kinds of Unity UGI implementations, only one can be imported into the project at one time. I saw u are using UGUI, so just delete ngui and fairgui. 

Close this issue. Reopen it if meet any problem.

**Comment by ahmedaniss25** [comment]
Problem Fixed here : https://youtu.be/28n9q8GG-gg
