### ISSUE TITLE
[Unity3D] isVRSupported 有误

### ISSUE THREAD

**Issue by HBoPRC** [AirtestProject/Poco-SDK#41]
使用低版本 Unity 时（5.6.4），UnityEngine.XR.XRSettings 报错；
希望这里做个版本区分，低版本下还是 UnityEngine.VR.VRSettings.

**Comment by adolli** [comment]
多谢反馈，我们兼容一下

**Comment by adolli** [comment]
更新一下最新的sdk就好了，由于旧版的u3d没有做vr方面的适配，所以我们只是暂时return了false，所以你应该没有用到vr方面的api吧，现在客户端不会报错了。

先close了，有问题再reopen

**Comment by HBoPRC** [comment]
> 更新一下最新的sdk就好了，由于旧版的u3d没有做vr方面的适配，所以我们只是暂时return了false，所以你应该没有用到vr方面的api吧，现在客户端不会报错了。
> 
> 先close了，有问题再reopen

Assets/Script/Unity3D/VRSupport.cs(41,23): error CS0234: The type or namespace name `XR' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
Assets/Script/Unity3D/VRSupport.cs(43,10): error CS0246: The type or namespace name `e' could not be found. Are you missing an assembly reference?

5.6.4版本还是会报错
