### ISSUE TITLE
ModuleNotFoundError: No module named 'poco'

### ISSUE THREAD

**Issue by yhhwatl** [AirtestProject/Poco-SDK#60]
Egret 
DZ417deMac-mini:roh5 dream001$ egret build -e
您正在使用白鹭编译器 5.2.31 版本
扫描项目列表
项目共计编译耗时：26.941秒
DZ417deMac-mini:roh5 dream001$ python -m poco.utils.net.stdbroker ws://*:5003 tcp://*:15004
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7: Error while finding module specification for 'poco.utils.net.stdbroker' (ModuleNotFoundError: No module named 'poco')
![image](https://user-images.githubusercontent.com/4963807/70427317-756e8e00-1aaf-11ea-9235-b2f1c584cc3d.png)

**Comment by yimelia** [comment]
pip list查看一下是不是安装的是`pocoui`？
`pip uninstall poco`
然后
`pip install pocoui`，后者才是正确的

**Comment by yhhwatl** [comment]
> pip list查看一下是不是安装的是`pocoui`？
> `pip uninstall poco`
> 然后
> `pip install pocoui`，后者才是正确的

谢谢 我用python2 -m 就好了
