### ISSUE TITLE
numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by terieqin** [AirtestProject/Poco-SDK#61]
## 环境
> python 3.7.4 64bit
> numpy == 1.17.3 / 1.18
> opencv-python == 4.1.2.30

网上都说这个错误是numpy版本太低，然而1.18已经是最新的了，我还特意降级到了1.17.3，还是不行。

**Comment by yimelia** [comment]
可以尝试下卸载opencv-python，然后装 `opencv-contrib-python<=3.4.2.17`
