### ISSUE TITLE
Newtonsoft.json被定义多次，删除又会报缺少引用

### ISSUE THREAD

**Issue by Macile** [AirtestProject/Poco-SDK#66]
添加pocosdk会报错，多重定义
![1————](https://user-images.githubusercontent.com/26572845/72501841-e2293500-3872-11ea-91a7-295da44feb71.png)
如果删除3rdLib文件夹又会报缺少引用

![2————](https://user-images.githubusercontent.com/26572845/72501874-fa994f80-3872-11ea-8cae-e26282868452.png)

**Comment by Linzecong** [comment]
https://poco.readthedocs.io/en/latest/source/doc/integration.html#unity3d

**Comment by Macile** [comment]
> https://poco.readthedocs.io/en/latest/source/doc/integration.html#unity3d

这是什么意思？我哪里操作不对？
我首先下载了poco的sdk
游戏用的UGUI所以删除其他的NGUI个FGUI
然后直接放入工程里
gameobject上挂载PocoManager.cs脚本
就这个顺序，完全按照官方来的
是有什么 地方操作不对吗

**Comment by Macile** [comment]
这是我的unity工程目录
![3--](https://user-images.githubusercontent.com/26572845/72503753-785f5a00-3877-11ea-8ab5-37a41fcd5f76.png)

**Comment by Linzecong** [comment]
Copy the Unity3D folder to your unity project **script** folder.

**Comment by Macile** [comment]
> 将Unity3D文件夹复制到您的统一项目**脚本**文件夹。
非常感谢，
由于我的脚本文件夹里没有Newtonsoft.Json.dll，他是在另外的目录，
我将它复制到了Newtonsoft.Json.dll所在的同级目录，报错解决了。
