### ISSUE TITLE
接入Poco-untiy3d的SDK，在ios手机中，渲染树中的控件没有信息 

### ISSUE THREAD

**Issue by tmac001** [AirtestProject/Poco-SDK#84]
ui环境：UGUI
在unity模式下能出现渲染树
但是打包后在手机中没有看到出现Poco服务启动的日志，并且不能再airtest ide中查看渲染树中的控件

**Comment by yimelia** [comment]
目前IDE的ios暂时不能拿到unity的UI树，这个问题正在修复，下个版本会尽快重新放出来

**Comment by tmac001** [comment]
但是我在ios包内，都没有看到Poco服务启动的日志。
我在untiy运行时能够正常看到，并且能够通过poco正常执行点击等操作

**Comment by yimelia** [comment]
对，目前ios的有问题，只有android和windows环境下可以

**Comment by tmac001** [comment]
好的，谢谢，问一下你们下个版本在什么时候
