### ISSUE TITLE
接入SDK后，寻找控件时报错“Material doesn't have a color property '_Color'”

### ISSUE THREAD

**Issue by hhhzhao** [AirtestProject/Poco-SDK#88]
工程文件接入poco sdk后，打开airtest的poco辅助窗，开始搜寻控件
循环刷报错：
“Material doesn't have a color property '_Color'"
之后游戏就会变得非常卡
测试设备：OPPO Reno 5K
Unity版本：2018.4.24f1
使用UI：UGUI

**Comment by fishfish-yu** [comment]
可以通过注释掉这部分的代码来解决![image](https://user-images.githubusercontent.com/55433784/119641768-93b77d80-be4c-11eb-92f4-fedc7095cd0e.png)
