### ISSUE TITLE
The type or namespace name 'AbstractNode' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by GuoDongRuiA** [AirtestProject/Poco-SDK#97]
把Unity3D文件夹拷贝到我的项目中，会报错
1.Assets\Unity3D\UnityDumper.cs(7,32): error CS0246: The type or namespace name '**AbstractDumper**' could not be found (are you missing a using directive or an assembly reference?)

2.Assets\Unity3D\ugui\UnityNode.cs(66,25): error CS0246: The type or namespace name '**AbstractNode**' could not be found (are you missing a using directive or an assembly reference?)
这是为啥啊？
[](url)

**Comment by yimelia** [comment]
这两个文件在sdk目录里，检查一下是不是漏放进去了
